services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devradar
      MYSQL_USER: devradar
      MYSQL_PASSWORD: devradar
    ports:
      - "3306:3306"
    volumes:
      - devradar-mysql:/var/lib/mysql
volumes:
  devradar-mysql:
